### ISSUE TITLE
no retweet/fave notifications?

### ISSUE THREAD

**Issue by cwage** [oysttyer/oysttyer#74] opened 2016-05-06 03:14 UTC
I think this might be something I've done, but I am no longer getting notifications in oysttyer for retweets or faves.. what controls that? are they not on by default?

**Comment by atomicules** [comment] 2016-05-06 07:08
Are you running master? I could have broken something related to my work on #57. Otherwise, I'm not sure. This should happen automatically as long as using streaming. I'll have to investigate.

**Comment by cwage** [comment] 2016-05-06 16:01
Yes, although I recently did a git pull to update because it was happening prior as well.. Not sure what I was running at that point. I can try to do some debugging later today -- if there's anything you want me to try, lemme know.

**Comment by cwage** [comment] 2016-05-06 16:50
It also seems to be acting very strangely/slowly -- even my own tweets don't appear until ~20-30s later sometimes. wondering if twitter changed something

**Comment by atomicules** [comment] 2016-05-06 18:54
I too have seen the slow updating thing. I am trying to track down the 
point that occurred. It seems hard to reproduce reliably. I _think_ it 
is something I've done on master somewhere around commit 
2a08d0cdaec834c4c38bf18dd752654d08096e70, but like I say, hard to 
pinpoint and reliably reproduce.

My advice would be to use the last release unless you fancy running 
each recent commit for a length of time (like I'm trying to do) to 
pinpoint what I've broken.

**Comment by cwage** [comment] 2016-05-07 00:38
gotcha -- is there a stable release branch?

**Comment by atomicules** [comment] 2016-05-07 10:28
No stable release branch, but tagged releases are intended to be 
stable. So I'd just check out v2.6.1.

**Comment by atomicules** [comment] 2016-05-07 10:54
As in `git checkout 2.6.1`

**Comment by atomicules** [comment] 2016-05-08 20:09
@cwage Running 2.6.1, are you now seeing rewteet/fav notifications? If so I'll close this out, because the bug is being tracked on #57.

**Comment by cwage** [comment] 2016-05-08 20:11
just checked it out -- i'll give it a whirl for a while and let you know

**Comment by cwage** [comment] 2016-05-08 20:25
no dice with 2.6.1 either

**Comment by atomicules** [comment] 2016-05-08 20:29
Hmmmm, ok, thanks. Really not sure what is going on there then. Maybe 
this is a separate issue. Perhaps something has changed on Twitter's 
end? I'll have to investigate further.

**Comment by atomicules** [comment] 2016-05-08 21:20
@cwage It's possibly (probably, hopefully!) this: [Retiring old (v1) Streaming API endpoints on March 31st, 2016](https://twittercommunity.com/t/retiring-old-v1-streaming-api-endpoints-on-march-31st-2016/60351). Apologies. Missed that one! :disappointed: 

I'll break out the bad #57 stuff into a separate branch and do a new release with the updated userstream end point. But probably can't do this until tomorrow. You could try fixing yourself in the meantime.

Change [this line](https://github.com/oysttyer/oysttyer/blob/d2d6af2976bab52a80b33d46cd7214458e365f4a/oysttyer.pl#L729) to: `https://userstream.twitter.com/1.1/user.json`

Note: if that does fix things, a huge thanks for bringing this to my attention.

**Comment by atomicules** [comment] 2016-05-08 21:24
Just did a brief test. I unliked some of my tweets from another account: no dice. But liking a new one did show up straight away. So this is probably the issue.

**Comment by cwage** [comment] 2016-05-08 21:25
Okay, I'll give it a whirl!

**Closed as completed** 2016-05-09 06:44 UTC
Labels: bug, question, in progress, hot!

**Comment by atomicules** [comment] 2016-05-09 08:36
@cwage I closed this out because I'm pretty sure it fixes it, but feel free to re-open if you disagree.
